apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepfake-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepfake-backend
  template:
    metadata:
      labels:
        app: deepfake-backend
    spec:
      containers:
        - name: deepfake-backend
          image: vignesg043/deepfake-backend:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: deepfake-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
